version: "3"
services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog-2
    ports:
      - 1025:1025
      - 8025:8025

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  product-db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product-db
    ports:
      - "5432:5432"

  users-db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users-db
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command:
      -p 5431

  shopping-cart-db:
    image: "postgres"
    container_name: "shopping-cart-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopping-cart-db
    expose:
      - "5434"
    ports:
      - "5434:5434"
    command:
      -p 5434

  order-db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order-db
    expose:
      - "5435"
    ports:
      - "5435:5435"
    command:
      -p 5435

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

#  service-discovery:
#    image: new-ecommerce-discovery-service
#    container_name: service-discovery
#    ports:
#      - "8761:8761"
#
#  api-gateway:
#    image: new-ecommerce-api-gateway
#    container_name: api-gateway
#    ports:
#      - "8090:8090"
#    depends_on:
#      - service-discovery
#    environment:
#      - EUREKA_URL=http://service-discovery:8761/eureka
#      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
#
#  user-service:
#    image: new-ecommerce-user-service
#    ports:
#      - "8082:8082"
#    depends_on:
#      - users-db
#      - service-discovery
#      - zipkin
#    environment:
#      - DB_URL=jdbc:postgresql://users-db:5431/users-db
#      - DB_USER=postgres
#      - DB_PASS=postgres
#      - EUREKA_URL=http://service-discovery:8761/eureka
#      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
#      - REDIS_URL=redis