version: "3"
services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog-2
    ports:
      - 1025:1025
      - 8025:8025
  users-db:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users-db
    expose:
      - "5431"
    ports:
      - "5431:5431"
    command:
      -p 5431

  user-service:
    image: test-image-user
    ports:
      - "8082:8082"
    depends_on:
      - users-db
    environment:
      - DB_URL=jdbc:postgresql://users-db:5431/users-db
      - DB_USER=postgres
      - DB_PASS=postgres