server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true


spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: 6379
  cache:
    type: redis

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

