apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.deploymentName }}
  labels:
    app: {{ .Values.backend.name }}
    tier: {{ .Values.backend.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
      tier: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        tier: {{ .Values.backend.name }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
          ports:
              - containerPort: {{ .Values.backend.port }}
          env:
            - name: ZIPKIN_URL
              value: http://zipkin:9411
            - name: EUREKA_URL
              value: http://servicediscoveryservice:8761/eureka
            - name: DB_URL
              value: jdbc:postgresql://product-postgres-postgres-service:5432/product-db
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: product-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: REDIS_URL
              value: redis
      restartPolicy: {{ .Values.backend.restartPolicy }}