apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgres
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
          - name: postgres
            args:
              - -p
              - "5435"
            image: {{ .Values.postgres.image }}
            env:
              - name: POSTGRES_USER
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Release.Name }}-configmap
                    key: POSTGRES_USER
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-secret
                    key: POSTGRES_PASSWORD
              - name: POSTGRES_DB
                valueFrom:
                  configMapKeyRef:
                    name: {{ .Release.Name }}-configmap
                    key: POSTGRES_DB
            ports:
              - containerPort: {{ .Values.postgres.port }}
