apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.backend.name }}
    tier: {{ .Values.backend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}