apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  selector:
    app: {{ .Release.Name }}-redis
  ports:
      - protocol: TCP
        port: {{ .Values.redis.port }}
        targetPort: {{ .Values.redis.port }}
