apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.deploymentName }}
  labels:
    app: {{ .Values.backend.name }}
    tier: {{ .Values.backend.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
      tier: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        tier: {{ .Values.backend.name }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
          ports:
              - containerPort: {{ .Values.backend.port }}
          env:
            - name: KAFKA_URL
              value: broker:9092
            - name: ZIPKIN_URL
              value: http://zipkin:9411/api/v2/spans
            - name: EUREKA_URL
              value: http://servicediscoveryservice:8761/eureka
            - name: MAILHOG
              value: mailhog
      restartPolicy: {{ .Values.backend.restartPolicy }}