apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
    - name: smtp
      protocol: TCP
      port: {{ .Values.service.smtpPort }}
      targetPort: {{ .Values.service.smtpPort }}
  selector:
    app: {{ .Values.name }}